# Quantumult X ImageTwist 图床穿透 Rewrite 配置 
# ==========================================================
# 仅保留用户提供的规则
# ==========================================================

#[rewrite_local]

# === ImageTwist ===
^https?://img(\d+)\.imagetwist\.com/th/(\d+)/(.+)$ url script-request-header imagetwist-all-in-one@https://raw.githubusercontent.com/kidddjh/quantumult-X/refs/heads/main/imagetwist-all-in-one.js
^https?://img(\d+)\.imagetwist\.com/i/(\d+)/(.+)$ url script-response-header imagetwist-all-in-one@https://raw.githubusercontent.com/kidddjh/quantumult-X/refs/heads/main/imagetwist-all-in-one.js

#[mitm]
hostname = img*.imagetwist.com
