hostname = *.imagetwist.com

# 1. 自动跳转高清原图 (th -> i)
^https?://(img\d+\.imagetwist\.com)/th/(.+) url 302 https://$1/i/$2

# 2. 调用 JS 脚本伪造 Referer 绕过防盗链
^https?://img\d+\.imagetwist\.com/i/ url-script-request https://raw.githubusercontent.com/kidddjh/quantumult-X/refs/heads/main/imagetwist.js