#!name=Image Rewrite
#!desc=图片重定向规则

[rewrite_remote]

hostname = imgtraffic.com, pixhost.to, xxxwebdlxxx.top, xxxwebdlxxx.org, imgxclub.com, pilot007.org

^https?:\/\/imgtraffic\.com\/.*\/1s\/(.*)$ 302 https://imgtraffic.com/$1
^https?:\/\/t2\.pixhost\.to\/thumbs\/(\d+)\/(.*)$ 302 https://img2.pixhost.to/images/$1/$2
^https?:\/\/t2\.pixhost\.to\/show\/(\d+)\/(.*)$ 302 https://img2.pixhost.to/images/$1/$2
^https?:\/\/xxxwebdlxxx\.top\/upload\/small\/(.*)$ 302 https://xxxwebdlxxx.top/upload/big/$1
^https?:\/\/xxxwebdlxxx\.org\/upload\/small\/(.*)$ 302 https://xxxwebdlxxx.org/upload/big/$1
^https?:\/\/imgxclub\.com\/ps\/(.*)$ 302 https://imgxclub.com/p/$1
^https?:\/\/pilot007\.org\/(.*)\.th\.(jpg|png|jpeg|gif)$ 302 https://pilot007.org/$1.$2