imgtraffic.com, ^https?:\/\/imgtraffic\.com\/.*\/1s\/(.*)$, 302, https://imgtraffic.com/$1
pixhost.to, ^https?:\/\/t2\.pixhost\.to\/thumbs\/(\d+)\/(.*)$, 302, https://img2.pixhost.to/images/$1/$2
pixhost.to, ^https?:\/\/t2\.pixhost\.to\/show\/(\d+)\/(.*)$, 302, https://img2.pixhost.to/images/$1/$2
xxxwebdlxxx.top, ^https?:\/\/xxxwebdlxxx\.top\/upload\/small\/(.*)$, 302, https://xxxwebdlxxx.top/upload/big/$1
xxxwebdlxxx.org, ^https?:\/\/xxxwebdlxxx\.org\/upload\/small\/(.*)$, 302, https://xxxwebdlxxx.org/upload/big/$1
imgxclub.com, ^https?:\/\/imgxclub\.com\/ps\/(.*)$, 302, https://imgxclub.com/p/$1
pilot007.org, ^https?:\/\/pilot007\.org\/(.*)\.th\.(jpg|png|jpeg|gif)$, 302, https://pilot007.org/$1.$2

