# Quantumult X 图床穿透 Rewrite 配置 (用户精简版)
# ==========================================================
# 仅保留用户提供的规则
# ==========================================================

[rewrite_local]

# === PixHost ===
^https?://(t|img)(\d*)\.pixhost\.to/(thumbs|show)/(\d+)/(.+)$ url 302 https://img$2.pixhost.to/images/$4/$5

[mitm]
hostname =  t*.pixhost.to, img*.pixhost.to
