[mitm]
hostname = %APPEND% xxxclub.to

[rewrite_local]
# XXXClub RSS 自动获取全文 (封面图+剧情+标签)
^https?:\/\/xxxclub\.to\/feed\/.*\.xml url script-response-body https://raw.githubusercontent.com/kidddjh/quantumult-X/refs/heads/main/xxxclub.js