[rewrite_local]
# 改写 RSS 响应体 (Body)
^https?:\/\/xxxclub\.to\/feed\/.*\.xml url script-response-body https://raw.githubusercontent.com/kidddjh/quantumult-X/refs/heads/main/xxxclub.js

# 改写图片请求头 (Header)
^https?:\/\/(imgxclub\.com|imgtraffic\.com)\/ url script-request-header https://raw.githubusercontent.com/kidddjh/quantumult-X/refs/heads/main/xxxclub.js

[mitm]
hostname = %APPEND% xxxclub.to, imgxclub.com, imgtraffic.com